"""add checked_bags and baggage_claims tables

Revision ID: 1ca1c18ce823
Revises: 7443f727249c
Create Date: 2026-09-03 23:00:41.768325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca1c18ce823'
down_revision: Union[str, Sequence[str], None] = '7443f727249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_bags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('tag_number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checked_bags_booking_id'), 'checked_bags', ['booking_id'], unique=False)
    op.create_index(op.f('ix_checked_bags_tag_number'), 'checked_bags', ['tag_number'], unique=True)
    op.create_table('baggage_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_number', sa.String(length=10), nullable=False),
    sa.Column('checked_bag_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('compensation_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checked_bag_id'], ['checked_bags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baggage_claims_checked_bag_id'), 'baggage_claims', ['checked_bag_id'], unique=False)
    op.create_index(op.f('ix_baggage_claims_claim_number'), 'baggage_claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_baggage_claims_user_id'), 'baggage_claims', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baggage_claims_user_id'), table_name='baggage_claims')
    op.drop_index(op.f('ix_baggage_claims_claim_number'), table_name='baggage_claims')
    op.drop_index(op.f('ix_baggage_claims_checked_bag_id'), table_name='baggage_claims')
    op.drop_table('baggage_claims')
    op.drop_index(op.f('ix_checked_bags_tag_number'), table_name='checked_bags')
    op.drop_index(op.f('ix_checked_bags_booking_id'), table_name='checked_bags')
    op.drop_table('checked_bags')
    # ### end Alembic commands ###
