"""make flight_selection_tokens.booking_id nullable

Revision ID: 7443f727249c
Revises: 94130a3fa630
Create Date: 2026-09-03 22:36:47.234552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7443f727249c'
down_revision: Union[str, Sequence[str], None] = '94130a3fa630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight_selection_tokens', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight_selection_tokens', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
