"""add departure_time, seats table, unique seat constraints

Revision ID: 7d9bf145d636
Revises: 9126f1c6c601
Create Date: 2026-08-12 17:55:28.045682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9bf145d636'
down_revision: Union[str, Sequence[str], None] = '9126f1c6c601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_number', name='uq_seat_flight_number')
    )
    op.create_index(op.f('ix_seats_flight_id'), 'seats', ['flight_id'], unique=False)
    op.create_unique_constraint('uq_booking_flight_seat', 'bookings', ['flight_id', 'seat'])
    op.add_column('flights', sa.Column('departure_time', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'departure_time')
    op.drop_constraint('uq_booking_flight_seat', 'bookings', type_='unique')
    op.drop_index(op.f('ix_seats_flight_id'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
