"""baseline: users, chats, flights, bookings

Revision ID: 9126f1c6c601
Revises: 
Create Date: 2026-08-12 16:30:49.537704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9126f1c6c601'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=10), nullable=False),
    sa.Column('passenger_name', sa.String(length=200), nullable=False),
    sa.Column('seat', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_confirmation_code'), 'bookings', ['confirmation_code'], unique=True)
    op.create_index(op.f('ix_bookings_flight_id'), 'bookings', ['flight_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected the checkpoint_* tables as "removed"
    # since they're not part of this app's SQLAlchemy Base.metadata — they're
    # owned and managed separately by langgraph's PostgresSaver (see
    # app/agentic_ai/graph.py). The drop_table/drop_index calls Alembic
    # generated for them have been deliberately removed from this migration;
    # do not let this or future autogenerate diffs touch checkpoint_* tables.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (checkpoint_* table recreation removed here too — see note in upgrade())
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_flight_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_confirmation_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
