"""add flight_selection_tokens table

Revision ID: 94130a3fa630
Revises: 7d9bf145d636
Create Date: 2026-08-12 18:45:09.806961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94130a3fa630'
down_revision: Union[str, Sequence[str], None] = '7d9bf145d636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_selection_tokens',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_selection_tokens_booking_id'), 'flight_selection_tokens', ['booking_id'], unique=False)
    op.create_index(op.f('ix_flight_selection_tokens_user_id'), 'flight_selection_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_selection_tokens_user_id'), table_name='flight_selection_tokens')
    op.drop_index(op.f('ix_flight_selection_tokens_booking_id'), table_name='flight_selection_tokens')
    op.drop_table('flight_selection_tokens')
    # ### end Alembic commands ###
